print("*****************")
file=open("tops1.txt ","w")
file.write("this is fail managment demo using Python.")
file.close()
print("Fail Written Successfully")
print("*****************")

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*****************")

file=open("tops1.txt","a")
file.write("\nThis fail is now appended.")
file.close()
print("fail Appended successfully")
print("*****************")

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*****************")

file=open("tops2.txt","w+")
file.write("this is W+ operater is python.")
print("Current Fail Position:",file.tell())
file.seek(0)
print(file.read())
file.close()

file=open("tops2.txt","r")
print(file.read())
file.close()
print("*****************")
